# Generated by Django 4.2.3 on 2023-07-26 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="item",
            fields=[
                (
                    "itemid",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("itemname", models.CharField(max_length=100)),
                ("price", models.IntegerField()),
                ("description", models.CharField(max_length=100)),
                ("pictureid", models.IntegerField()),
            ],
        ),
    ]
